image:
  file: .gitpod/Dockerfile

tasks:
  - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
  - init: |
      flutter channel stable
      flutter upgrade
      flutter precache

      flutter doctor
      flutter pub get

  - command: |
      flutter devices
      flutter run --web-port 8080

ports:
  - port: 5900
    onOpen: ignore
    # VNC
  - port: 6080
    onOpen: open-browser
    # Flutter Web
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
