image:
  file: .gitpod/Dockerfile

tasks:
   - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
   - init: |
      flutter channel stable
      flutter upgrade
      flutter precache

      flutter doctor
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    # VNC
  - port: 6080
    onOpen: ignore
    visibility: public
    # Flutter Web
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 9100
    onOpen: ignore
  - port: 9101
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
