image:
  file: .gitpod/Dockerfile

tasks:
  - before: sudo mount -t tmpfs shm -osize=4096m /dev/shm
  - init: |
      flutter doctor
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    visibility: public
    name: VNC Server
  - port: 6080
    onOpen: ignore
    visibility: public
    name: VNC Client
    description: noVNC web client
  - port: 8080
    onOpen: ignore
    visibility: public
    name: Flutter Web
    description: Where Flutter serves the web app
  - port: 9100
    onOpen: ignore
  - port: 9101
    onOpen: ignore
  - port: 49090
    onOpen: ignore
    visibility: public
    name: Flutter DevTools
  - port: 49191
    onOpen: ignore
    visibility: public
    name: Flutter DDS

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
